environment:
  machine_user: vagrant
  machine_pass: vagrant
  KITCHEN_YAML: kitchen.appveyor.yml

branches:
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

#faster cloning
clone_depth: 1

# Install the latest current build of Chef Workstation
install:
  - ps: (& cmd /c); iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chef-workstation -channel current
  - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
  - ps: $PSVersionTable
  - ps: $Env:Path += "C:\opscode\chef\bin;C:\opscode\chef-workstation\bin"
  - ps: $Env:CHEF_LICENSE = "accept"
  - ps: c:\opscode\chef-workstation\bin\chef.exe shell-init powershell --chef-license accept
  - ps: c:\opscode\chef-workstation\bin\chef.exe exec ruby --version
  - ps: secedit /export /cfg $env:temp/export.cfg
  - ps: ((get-content $env:temp/export.cfg) -replace ('PasswordComplexity = 1', 'PasswordComplexity = 0')) | Out-File $env:temp/export.cfg
  - ps: ((get-content $env:temp/export.cfg) -replace ('MinimumPasswordLength = 8', 'MinimumPasswordLength = 0')) | Out-File $env:temp/export.cfg
  - ps: secedit /configure /db $env:windir/security/new.sdb /cfg $env:temp/export.cfg /areas SECURITYPOLICY
  - ps: net user /add $env:machine_user $env:machine_pass
  - ps: net localgroup administrators $env:machine_user /add

build_script:
  - ps: c:\opscode\chef-workstation\bin\chef.exe shell-init powershell --chef-license=accept | iex; cmd /c c:\opscode\chef-workstation\bin\chef.exe --version

before_test:
  - ps: gc:\opscode\chef-workstation\bin\chef.exe shell-init powershell --chef-license=accept | iex; cmd /c c:\opscode\chef-workstation\bin\chef.exe gem install inspec_tools --no-document

test_script:
  - ps: c:\opscode\chef-workstation\bin\chef.exe --version
  - ps: c:\opscode\chef-workstation\bin\chef.exe exec kitchen verify; echo 1;
  - ps: $results = $(ls *results.json)
  - ps: c:\opscode\chef-workstation\bin\chef.exe exec inspec_tools summary -j $results -c
  - ps: c:\opscode\chef-workstation\bin\chef.exe exec inspec_tools compliance -j $results -f .\threshold.yml

artifacts:
  - path: '*results.json'

deploy: off
