jobs:
  container:
    runs-on: ubuntu-latest
    container: chef/chefworkstation
    steps:
      - name: Display the path
        run: echo $PATH
      - name: Get InSpec Version
        run: inspec -v
