name: InSpec Check

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  container:
    runs-on: ubuntu-latest
    container: chef/chefworkstation
    steps:
      - name: Display the path
        run: echo $PATH
      - name: Get InSpec Version
        run: inspec -v
